fix: errors

diff --git a/nbd b/nbd
--- a/nbd
+++ b/nbd
@@ -82,7 +82,12 @@ domount() {
 
 	mkdir -p "${MNTPATH}" &> /dev/null
 
-    modprobe nbd
+    modprobe nbd 2> /dev/null
+	if [ $? -ne 0 ]; then
+		err "{ \"status\": \"Failure\", \"message\": \"Failed to load nbd module\"}"
+		exit 1
+	fi
+
     NBDNUMBERS="$(ls -1 /dev/nbd[0-9]* | grep -o [0-9]* | sort -h)"
     NBDDEVICE="$(for i in $NBDNUMBERS; do
                      if fdisk -l "/dev/nbd$i" 2>&1 | grep -q 'Inappropriate ioctl for device'; then
@@ -97,7 +102,7 @@ domount() {
     fi
 
     echo "${NBDDEVICE}" > "${MNTPATH}.device"
-    qemu-nbd -f raw -c "${NBDDEVICE}" "${FILE}"
+    qemu-nbd -f raw -c "${NBDDEVICE}" "${FILE}" &>/dev/null
 	if [ $? -ne 0 ]; then
 		err "{ \"status\": \"Failure\", \"message\": \"Failed to setup nbd device ${NBDDEVICE} from ${FILE}\"}"
 		exit 1
@@ -106,7 +111,7 @@ domount() {
 	mount "${NBDDEVICE}" "${MNTPATH}" &> /dev/null
 	if [ $? -ne 0 ]; then
 		err "{ \"status\": \"Failure\", \"message\": \"Failed to mount device ${NBDDEVICE} from ${FILE} at ${MNTPATH}\"}"
-        qemu-nbd -d "${NBDDEVICE}"
+        qemu-nbd -d "${NBDDEVICE}" &>/dev/null
 		exit 1
 	fi
 
@@ -125,7 +130,7 @@ unmount() {
     fi
 
     if [ -f ${MNTPATH}.device ]; then
-        qemu-nbd -d "$(cat ${MNTPATH}.device)"
+        qemu-nbd -d "$(cat ${MNTPATH}.device)" &>/dev/null
         rm -f ${MNTPATH}.device
     fi
 
