fix: tabs

diff --git a/nbd b/nbd
--- a/nbd
+++ b/nbd
@@ -18,32 +18,32 @@
 #  - Please install "jq" package before using this driver.
 
 usage() {
-	err "Invalid usage. Usage: "
-	err "\t$0 init"
-	err "\t$0 mountdevice <mount dir> <mount device> <json params>"
-	err "\t$0 unmountdevice <mount dir>"
-	exit 1
+    err "Invalid usage. Usage: "
+    err "\t$0 init"
+    err "\t$0 mountdevice <mount dir> <mount device> <json params>"
+    err "\t$0 unmountdevice <mount dir>"
+    exit 1
 }
 
 err() {
-	echo -ne $* 1>&2
+    echo -ne $* 1>&2
 }
 
 log() {
-	echo -ne $* >&1
+    echo -ne $* >&1
 }
 
 domount() {
-	MNTPATH=$1
-	SHARE=$(echo $2 | jq -r '.share')
-	FILE=$(echo $2 | jq -r '.file')
-	FSTYPE=$(echo $2 | jq -r '.["kubernetes.io/fsType"]')
-	MMP=$(echo $2 | jq -r '.mmp')
-	SIZE=$(echo $2 | jq -r '.size' | tr '[:lower:]' '[:upper:]')
-	FSCK=$(echo $2 | jq -r '.fsck')
+    MNTPATH=$1
+    SHARE=$(echo $2 | jq -r '.share')
+    FILE=$(echo $2 | jq -r '.file')
+    FSTYPE=$(echo $2 | jq -r '.["kubernetes.io/fsType"]')
+    MMP=$(echo $2 | jq -r '.mmp')
+    SIZE=$(echo $2 | jq -r '.size' | tr '[:lower:]' '[:upper:]')
+    FSCK=$(echo $2 | jq -r '.fsck')
     MMP_INTERVAL=$(echo $3 | jq -r '.mmpUpdateInterval')
-	FSCK_OPTIONS=$(echo $2 | jq -r '.fsck_options')
-	MOUNT_OPTIONS=$(echo $2 | jq -r '.mount_options')
+    FSCK_OPTIONS=$(echo $2 | jq -r '.fsck_options')
+    MOUNT_OPTIONS=$(echo $2 | jq -r '.mount_options')
 
     case null in
         ${MMP_INTERVAL} ) MMP_INTERVAL=5  ;&
@@ -51,42 +51,42 @@ domount() {
         ${MOUNT_OPTIONS} ) MOUNT_OPTIONS="" ;;
     esac
 
-	if [ "${SHARE}" != "null" ]; then
-		if ! mountpoint -q "${SHARE}"; then
-			err "{ \"status\": \"Failed\", \"message\": \"${SHARE} is not mounted\"}"
-			exit 0
-		fi
-		FILE="${SHARE}/${FILE}"
-	fi
+    if [ "${SHARE}" != "null" ]; then
+        if ! mountpoint -q "${SHARE}"; then
+            err "{ \"status\": \"Failed\", \"message\": \"${SHARE} is not mounted\"}"
+            exit 0
+        fi
+        FILE="${SHARE}/${FILE}"
+    fi
 
     if [[ "${MMP}" != +(false|no|0) ]] && [ "${FSTYPE}" == "ext4" ]; then
-		MMP_OPT="-O mmp -E mmp_update_interval=${MMP_INTERVAL}"
-	fi
+        MMP_OPT="-O mmp -E mmp_update_interval=${MMP_INTERVAL}"
+    fi
 
-	if [ ! -f "${FILE}" ]; then
-	    if [ -z "${SIZE}" ]; then
-		err "{\"status\": \"Failure\", \"message\": \"${FILE} does not exist\"}"
-		exit 1
-            else
-                mkdir -p "$(dirname "${FILE}")"
-                truncate -s ${SIZE} "${FILE}"
-            fi
-	fi
+    if [ ! -f "${FILE}" ]; then
+        if [ -z "${SIZE}" ]; then
+            err "{\"status\": \"Failure\", \"message\": \"${FILE} does not exist\"}"
+            exit 1
+        else
+            mkdir -p "$(dirname "${FILE}")"
+            truncate -s ${SIZE} "${FILE}"
+        fi
+    fi
 
-	if mountpoint -q "${MNTPATH}"; then
-		log "{\"status\": \"Success\"}"
-		exit 0
-	fi
+    if mountpoint -q "${MNTPATH}"; then
+        log "{\"status\": \"Success\"}"
+        exit 0
+    fi
 
-	VOLFSTYPE=`blkid -o udev ${FILE} 2>/dev/null|grep "ID_FS_TYPE"|cut -d"=" -f2`
-	if [ "${VOLFSTYPE}" == "" ]; then
+    VOLFSTYPE=`blkid -o udev ${FILE} 2>/dev/null|grep "ID_FS_TYPE"|cut -d"=" -f2`
+    if [ "${VOLFSTYPE}" == "" ]; then
 
-		mkfs -t ${FSTYPE} ${MMP_OPT} ${FILE} >/dev/null 2>&1
-		if [ $? -ne 0 ]; then
-			err "{ \"status\": \"Failure\", \"message\": \"Failed to create fs ${FSTYPE} on device ${FILE}\"}"
-			exit 1
-		fi
-	fi
+        mkfs -t ${FSTYPE} ${MMP_OPT} ${FILE} >/dev/null 2>&1
+        if [ $? -ne 0 ]; then
+            err "{ \"status\": \"Failure\", \"message\": \"Failed to create fs ${FSTYPE} on device ${FILE}\"}"
+            exit 1
+        fi
+    fi
 
     if [[ "${FSCK}" != +(false|no|0) ]]; then
         fsck -${FSCK_OPTIONS} -t ${FSTYPE} ${FILE} &> /dev/null
@@ -96,13 +96,13 @@ domount() {
         fi
     fi
 
-	mkdir -p "${MNTPATH}" &> /dev/null
+    mkdir -p "${MNTPATH}" &> /dev/null
 
     modprobe nbd 2> /dev/null
-	if [ $? -ne 0 ]; then
-		err "{ \"status\": \"Failure\", \"message\": \"Failed to load nbd module\"}"
-		exit 1
-	fi
+    if [ $? -ne 0 ]; then
+        err "{ \"status\": \"Failure\", \"message\": \"Failed to load nbd module\"}"
+        exit 1
+    fi
 
     # Check if nbd device already connected
     NBDDEVICE="$(ps aux | sed -n "s|.*qemu-nbd -f raw -c \(/dev/nbd[0-9]\+\) ${FILE}\$|\1|p" | head -n1)"
@@ -118,8 +118,8 @@ domount() {
         done
 
         if [ -z "${NBDDEVICE}" ]; then
-    		err "{\"status\": \"Failure\", \"message\": \"Free nbd device was not found\"}"
-    		exit 1
+            err "{\"status\": \"Failure\", \"message\": \"Free nbd device was not found\"}"
+            exit 1
         fi
     
         qemu-nbd -f raw -c "${NBDDEVICE}" "${FILE}" &>/dev/null
@@ -130,66 +130,66 @@ domount() {
         fi
     fi
 
-	mount -o "${MOUNT_OPTIONS}" "${NBDDEVICE}" "${MNTPATH}" &> /dev/null
-	if [ $? -ne 0 ]; then
-		err "{ \"status\": \"Failure\", \"message\": \"Failed to mount device ${NBDDEVICE} from ${FILE} at ${MNTPATH}\"}"
+    mount -o "${MOUNT_OPTIONS}" "${NBDDEVICE}" "${MNTPATH}" &> /dev/null
+    if [ $? -ne 0 ]; then
+        err "{ \"status\": \"Failure\", \"message\": \"Failed to mount device ${NBDDEVICE} from ${FILE} at ${MNTPATH}\"}"
         qemu-nbd -d "${NBDDEVICE}" &>/dev/null
-		exit 1
-	fi
+        exit 1
+    fi
 
-	log "{\"status\": \"Success\"}"
-	exit 0
+    log "{\"status\": \"Success\"}"
+    exit 0
 }
 
 unmount() {
-	MNTPATH=$1
+    MNTPATH=$1
     NBDDEVICE=$(mount | awk "\$3 == \"$(readlink -f $MNTPATH)\" {print \$1}" | head -n 1)
 
-	if [ -d ${MNTPATH} ] && mountpoint -q "${MNTPATH}"; then
-	    umount ${MNTPATH} &> /dev/null
-	    if [ $? -ne 0 ]; then
-	        err "{ \"status\": \"Failed\", \"message\": \"Failed to unmount volume at ${MNTPATH}\"}"
-	        exit 1
-	    fi
+    if [ -d ${MNTPATH} ] && mountpoint -q "${MNTPATH}"; then
+        umount ${MNTPATH} &> /dev/null
+        if [ $? -ne 0 ]; then
+            err "{ \"status\": \"Failed\", \"message\": \"Failed to unmount volume at ${MNTPATH}\"}"
+            exit 1
+        fi
     fi
 
     if [ ! -z ${NBDDEVICE} ]; then
         qemu-nbd -d ${NBDDEVICE} &>/dev/null
     fi
 
-	log "{\"status\": \"Success\"}"
+    log "{\"status\": \"Success\"}"
 
-	exit 0
+    exit 0
 }
 
 op=$1
 
 if ! command -v jq >/dev/null 2>&1; then
-	err "{ \"status\": \"Failure\", \"message\": \"'jq' binary not found. Please install jq package before using this driver\"}"
-	exit 1
+    err "{ \"status\": \"Failure\", \"message\": \"'jq' binary not found. Please install jq package before using this driver\"}"
+    exit 1
 fi
 
 if [ "$op" = "init" ]; then
-        log '{"status": "Success", "capabilities": {"attach": false}}'
-	exit 0
+    log '{"status": "Success", "capabilities": {"attach": false}}'
+    exit 0
 fi
 
 if [ $# -lt 2 ]; then
-	usage
+    usage
 fi
 
 shift
 
 case "$op" in
-	mount)
-		domount $*
-		;;
-	unmount)
-		unmount $*
-		;;
-	*)
-		log "{ \"status\": \"Not supported\" }"
-		exit 0
+    mount)
+        domount $*
+        ;;
+    unmount)
+        unmount $*
+        ;;
+    *)
+        log "{ \"status\": \"Not supported\" }"
+        exit 0
 esac
 
 exit 1
