upd: not use temp files

diff --git a/nbd b/nbd
--- a/nbd
+++ b/nbd
@@ -89,28 +89,30 @@ domount() {
 		exit 1
 	fi
 
-    NBDNUMBERS="$(ls -1 /dev/nbd[0-9]* | grep -o [0-9]* | sort -h)"
-    for i in $NBDNUMBERS; do
-        if fdisk -l "/dev/nbd$i" 2>&1 | grep -q 'Inappropriate ioctl for device' && mkfifo /run/lock/qemu-nbd-nbd$i 2> /dev/null; then
+    # Check if nbd device already connected
+    NBDDEVICE="$(ps aux | sed -n "s|.*qemu-nbd -f raw -c \(/dev/nbd[0-9]\+\) ${FILE}\$|\1|p" | head -n1)"
 
-            NBDDEVICE="/dev/nbd$i"
-            echo "${NBDDEVICE}" > "${MNTPATH}.device"
-
-
-            break
-        fi
-    done
-
+    # Find and connect new nbd device
     if [ -z "${NBDDEVICE}" ]; then
-		err "{\"status\": \"Failure\", \"message\": \"Free nbd device was not found\"}"
-		exit 1
-    fi
+        NBDNUMBERS="$(ls -1 /dev/nbd[0-9]* | grep -o [0-9]* | sort -h)"
+        for i in $NBDNUMBERS; do
+            if fdisk -l "/dev/nbd$i" 2>&1 | grep -q 'Inappropriate ioctl for device' && mkfifo /run/lock/qemu-nbd-nbd$i 2> /dev/null; then
+                NBDDEVICE="/dev/nbd$i"
+                break
+            fi
+        done
 
-    qemu-nbd -f raw -c "${NBDDEVICE}" "${FILE}" &>/dev/null
-
-    if [ $? -ne 0 ]; then
-        err "{ \"status\": \"Failure\", \"message\": \"Failed to setup nbd device "${NBDDEVICE}" from ${FILE}\"}"
-        exit 1
+        if [ -z "${NBDDEVICE}" ]; then
+    		err "{\"status\": \"Failure\", \"message\": \"Free nbd device was not found\"}"
+    		exit 1
+        fi
+    
+        qemu-nbd -f raw -c "${NBDDEVICE}" "${FILE}" &>/dev/null
+    
+        if [ $? -ne 0 ]; then
+            err "{ \"status\": \"Failure\", \"message\": \"Failed to setup nbd device "${NBDDEVICE}" from ${FILE}\"}"
+            exit 1
+        fi
     fi
 
     case "${FSCK}" in
@@ -139,6 +141,8 @@ domount() {
 
 unmount() {
 	MNTPATH=$1
+    NBDDEVICE=$(mount | awk "\$3 == \"$(readlink -f $MNTPATH)\" {print \$1}" | head -n 1)
+
 	if [ -d ${MNTPATH} ] && mountpoint -q "${MNTPATH}"; then
 	    umount ${MNTPATH} &> /dev/null
 	    if [ $? -ne 0 ]; then
@@ -147,9 +151,8 @@ unmount() {
 	    fi
     fi
 
-    if [ -f ${MNTPATH}.device ]; then
-        qemu-nbd -d "$(cat ${MNTPATH}.device)" &>/dev/null
-        rm -f ${MNTPATH}.device
+    if [ ! -z ${NBDDEVICE} ]; then
+        qemu-nbd -d ${NBDDEVICE} &>/dev/null
     fi
 
 	log "{\"status\": \"Success\"}"
